[package]
name = "file-crypto"
version = "0.1.1"
edition = "2018"

[dependencies]
ring = "0"
base64 = "0"
memmap = "0"
clap = "2"
byteorder = "1"

[dev-dependencies]
walkdir = "2"

[lib]
name = "file_crypto"
path = "src/lib.rs"

[[bin]]
name = "file-crypto"
path = "src/main.rs"